const products = [
    {
        id: 10000000001,
        title: 'Bả bẫy mối XTERM',
        price: 945000,
        priceSales: 850000,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'SALE',
        img: '',
        key: ['bả bẫy mối', 'xterm', 'bả bẫy mối xterm'],
        description: 'Bả bẫy mối XTERM là sản phẩm chuyên dùng để kiểm soát mối hiệu quả.',
    },
    {
        id: 10000000002,
        title: 'Tinh dầu Chanh Viet Oils',
        price: 1062500,
        priceSales: 950000,
        category: 'Sản phẩm giải pháp vệ sinh',
        status: 'SALE',
        img: '',
        key: ['tinh dầu chanh', 'viet oils', 'tinh dầu chanh viet oils'],
        description: 'Tinh dầu Chanh Viet Oils giúp làm sạch và khử mùi hiệu quả.',
    },
    {
        id: 10000000003,
        title: 'Hóa chất tẩy kính',
        price: 315000,
        priceSales: null,
        category: 'Sản phẩm dịch vụ vệ sinh',
        status: 'HOT',
        img: '',
        key: ['hóa chất tẩy kính', 'tẩy kính'],
        description: 'Hóa chất tẩy kính giúp làm sạch kính hiệu quả.',
    },
    {
        id: 10000000004,
        title: 'Thuốc diệt kiến',
        price: 300000,
        priceSales: null,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'HOT',
        img: '',
        key: ['thuốc diệt kiến', 'diệt kiến'],
        description: 'Thuốc diệt kiến giúp diệt kiến hiệu quả.',
    },
    {
        id: 10000000005,
        title: 'Bả bẫy chuột',
        price: 200000,
        priceSales: null,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'HOT',
        img: '',
        key: ['bả bẫy chuột', 'bả chuột'],
        description: 'Bả bẫy chuột giúp bắt chuột hiệu quả.',
    },
    {
        id: 10000000006,
        title: 'Bả bẫy muỗi',
        price: 200000,
        priceSales: null,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'HOT',
        img: '',
        key: ['bả bẫy muỗi', 'bả muỗi'],
        description: 'Bả bẫy muỗi giúp bắt muỗi hiệu quả.',
    },
    {
        id: 10000000007,
        title: 'Bả bẫy ruồi',
        price: 200000,
        priceSales: null,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'HOT',
        img: '',
        key: ['bả bẫy ruồi', 'bả ruồi'],
        description: 'Bả bẫy ruồi giúp bắt ruồi hiệu quả.',
    },
    {
        id: 10000000008,
        title: 'Bả bẫy gián',
        price: 200000,
        priceSales: 190000,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'SALE',
        img: '',
        key: ['bả bẫy gián', 'bả gián'],
        description: 'Bả bẫy gián giúp bắt gián hiệu quả.',
    },
    {
        id: 10000000009,
        title: 'Bả bẫy muỗi',
        price: 200000,
        priceSales: 190000,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'SALE',
        img: '',
        key: ['bả bẫy muỗi', 'bả muỗi'],
        description: 'Bả bẫy muỗi giúp bắt muỗi hiệu quả.',
    },
    {
        id: 1000000010,
        title: 'Bả bẫy ruồi',
        price: 200000,
        priceSales: 190000,
        category: 'Sản phẩm kiểm soát côn trùng',
        status: 'SALE',
        img: '',
        key: ['bả bẫy ruồi', 'bả ruồi'],
        description: 'Bả bẫy ruồi giúp bắt ruồi hiệu quả.',
    },
];

export { products };
