export const GET_USER = 'GET_USER';
export const SIGN_IN = 'SIGN_IN';
export const GET_BUTTON = 'GET_BUTTON';
export const GET_PRODUCT_PAGE = 'GET_PRODUCT_PAGE';
export const GET_PRODUCT_PAGE_SUCCESS = 'GET_PRODUCT_PAGE_SUCCESS';
export const ORDER_BEHAVIOR = 'ORDER_BEHAVIOR';
export const GET_BLOG_PAGE = 'GET_BLOG_PAGE';
export const GET_BLOG_PAGE_SUCCESS = 'GET_BLOG_PAGE_SUCCESS';

// Update user
export const UPDATE_SESSION_USER = 'UPDATE_SESSION_USER';

// all product
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

// Product

export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

// Blog

export const GET_BLOGS = 'GET_BLOGS';
export const ADD_BLOGS = 'ADD_BLOGS';
export const REMOVE_BLOGS = 'REMOVE_BLOGS';
export const UPDATE_BLOGS = 'UPDATE_BLOGS';
export const ADD_BLOGS_SUCCESS = 'ADD_BLOGS_SUCCESS';
export const REMOVE_BLOGS_SUCCESS = 'REMOVE_BLOGS_SUCCESS';
export const UPDATE_BLOGS_SUCCESS = 'UPDATE_BLOGS_SUCCESS';

// Cart
export const GET_CART = 'GET_CART';
export const ADD_CART = 'ADD_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const REMOVE_CART_ALL = 'REMOVE_CART_ALL';

// Cart
export const GET_MANAGEMENT = 'GET_MANAGEMENT';
export const ADD_MANAGEMENT = 'ADD_MANAGEMENT';
export const REMOVE_MANAGEMENT = 'REMOVE_MANAGEMENT';
export const UPDATE_MANAGEMENT = 'UPDATE_MANAGEMENT';
export const ADD_MANAGEMENT_SUCCESS = 'ADD_MANAGEMENT_SUCCESS';
export const REMOVE_MANAGEMENT_SUCCESS = 'REMOVE_MANAGEMENT_SUCCESS';
export const UPDATE_MANAGEMENT_SUCCESS = 'UPDATE_MANAGEMENT_SUCCESS';

// Orther
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const GET_BLOG_COMMENT = 'GET_BLOG_COMMENT';
export const ADD_BLOG_COMMENT = 'ADD_BLOG_COMMENT';
export const ADD_BLOG_COMMENT_SUCCESS = 'ADD_BLOG_COMMENT_SUCCESS';
export const DELETE_BLOG_COMMENT = 'DELETE_BLOG_COMMENT';
export const DELETE_BLOG_COMMENT_SUCCESS = 'DELETE_BLOG_COMMENT_SUCCESS';
export const GET_PROVINCE = 'GET_PROVINCE';

// Order
export const GET_ORDER = 'GET_ORDER';
export const GET_ADMIN_ORDER = 'GET_ADMIN_ORDER';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const REMOVE_ORDER_SUCCESS = 'REMOVE_ORDER_SUCCESS';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const REMOVE_ORDER_ALL = 'REMOVE_ORDER_ALL';

// Email
export const GET_EMAIL = 'GET_EMAIL';
export const ADD_EMAIL = 'ADD_EMAIL';
export const ADD_EMAIL_SUCCESS = 'ADD_EMAIL_SUCCESS';
export const ADD_EMAIL_FAIL = 'ADD_EMAIL_FAIL';
export const REMOVE_EMAIL = 'REMOVE_EMAIL';
export const REMOVE_EMAIL_SUCCESS = 'REMOVE_EMAIL_SUCCESS';
export const REMOVE_EMAIL_FAIL = 'REMOVE_EMAIL_FAIL';

// ImageWorK
export const ADD_IMG_WORK = 'ADD_IMG_WORK';
export const ADD_IMG_WORK_SUCCESS = 'ADD_IMG_WORK_SUCCESS';
export const ADD_IMG_WORK_FAIL = 'ADD_IMG_WORK_FAIL';
export const DELETE_IMG_WORK = 'DELETE_IMG_WORK';
export const DELETE_IMG_WORK_SUCCESS = 'DELETE_IMG_WORK_SUCCESS';
export const DELETE_IMG_WORK_FAIL = 'DELETE_IMG_WORK_FAIL';
export const UPDATE_IMG_WORK = 'UPDATE_IMG_WORK';
export const UPDATE_IMG_WORK_SUCCESS = 'UPDATE_IMG_WORK_SUCCESS';
export const UPDATE_IMG_WORK_FAIL = 'UPDATE_IMG_WORK_FAIL';
export const GET_IMG_WORK = 'GET_IMG_WORK';
export const GET_IMG_WORK_BY_TYPE = 'GET_IMG_WORK_BY_TYPE';
// Message
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

// GET Notification
export const GET_NOTIFICATION = 'GET_NOTIFICATION';

// GET Discount
export const GET_DISCOUNT = 'GET_DISCOUNT';
export const ADD_DISCOUNT = 'ADD_DISCOUNT';
export const ADD_DISCOUNT_SUCCESS = 'ADD_DISCOUNT_SUCCESS';
export const REMOVE_DISCOUNT_SUCCESS = 'REMOVE_DISCOUNT_SUCCESS';

// NOTIFICATIONS
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const ADD_NOTIFICATION_FAIL = 'ADD_NOTIFICATION_FAIL';
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_ALL_NOTIFICATIONS_BY_ID = 'GET_ALL_NOTIFICATIONS_BY_ID';
export const GET_ALL_NOTIFICATIONS_BY_ID_SUCCESS = 'GET_ALL_NOTIFICATIONS_BY_ID_SUCCESS';
export const GET_ALL_NOTIFICATIONS_BY_ID_FAIL = 'GET_ALL_NOTIFICATIONS_BY_ID_FAIL';
