import type { Metadata } from 'next';
import './globals.css';
import { Merriweather } from 'next/font/google';
import MuiSetUp from '../common/Mui/MuiSetup';

const inter = Merriweather({ subsets: ['latin'], weight: ['300', '400', '700'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MuiSetUp>{children}</MuiSetUp>
            </body>
        </html>
    );
}
